import asyncio
import sys
if sys.platform == "win32":
    asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())

try:
    __import__('pysqlite3')
    import sys
    sys.modules['sqlite3'] = sys.modules.pop('pysqlite3')
except ImportError:
    pass

import json
import os
import uuid

import streamlit as st
from dotenv import load_dotenv

load_dotenv()

from agent_graph import agent, AgentState
from rate_limiter import RateLimitError

# --- Page Configuration ---
st.set_page_config(
    page_title="LegalAI - Agentic RAG & Contract Analyzer",
    page_icon="⚖️",
    layout="wide"
)

# --- Session State Initialization ---
if "messages" not in st.session_state:
    st.session_state.messages = []
if "mode" not in st.session_state:
    st.session_state.mode = "legal"
if "current_thread" not in st.session_state:
    st.session_state.current_thread = str(uuid.uuid4())
if "thread_title" not in st.session_state:
    st.session_state.thread_title = "New Chat"

# --- Sidebar ---
with st.sidebar:
    st.title("LegalAI")
    st.markdown("---")
with st.sidebar:
    st.title("⚙️ Rate Limit Status")
    
    # Show current usage
    try:
        from rate_limiter import api_rate_limiter
        status = api_rate_limiter.get_status()
        
        st.metric("Requests/Minute", status['rpm'])
        st.metric("Requests/Day", status['rpd'])
        st.metric("Tokens/Minute", status['tpm'])
        
        # Warning if close to limit
        if int(status['rpm'].split('/')[0]) >= 3:
            st.warning("⚠️ Approaching RPM limit!")
        if int(status['rpd'].split('/')[0]) >= 12:
            st.error("🚨 Close to daily limit!")
            
    except Exception as e:
        st.error(f"Error fetching status: {e}")
    
    st.divider()
    
    st.subheader("Agent Mode")
    mode = st.radio(
        "Select Mode:",
        ["Legal Advisor (RAG)", "Contract Analyzer"],
        index=0 if st.session_state.mode == "legal" else 1
    )
    st.session_state.mode = "legal" if mode == "Legal Advisor (RAG)" else "contract"
    
    st.markdown("---")
    
    if st.button("➕ New Chat", use_container_width=True):
        st.session_state.messages = []
        st.session_state.current_thread = str(uuid.uuid4())
        st.session_state.thread_title = "New Chat"
        st.rerun()
        
    st.markdown("---")
    st.caption(f"Thread ID: `{st.session_state.current_thread[:8]}...`")
    
    st.markdown("### About")
    st.info(
        "LegalAI uses a multi-agent LangGraph architecture. "
        "In **Legal Advisor** mode, it uses Hybrid RAG (Dense + BM25 + RRF) to answer questions based on Indian Law. "
        "In **Contract Analyzer** mode, it extracts risks, clauses, and provides JSON-structured analysis."
    )

# --- Main Chat Interface ---
st.title(f"💬 {st.session_state.thread_title}")

# Display chat messages from history
for message in st.session_state.messages:
    with st.chat_message(message["role"]):
        st.markdown(message["content"])

# Chat input
placeholder = "Ask a legal question..." if st.session_state.mode == "legal" else "Paste your contract text here for analysis..."

if prompt := st.chat_input(placeholder):
    if st.session_state.thread_title == "New Chat" and st.session_state.mode == "legal":
        st.session_state.thread_title = prompt[:30] + "..." if len(prompt) > 30 else prompt

    st.session_state.messages.append({"role": "user", "content": prompt})
    with st.chat_message("user"):
        st.markdown(prompt)

    spinner_text = "Agentic RAG reasoning…" if st.session_state.mode == "legal" else "Analyzing contract…"
    with st.spinner(spinner_text):
        try:
            # FIXED: Pass FULL conversation history, not just current prompt
            input_state = AgentState(
                messages=st.session_state.messages, 
                mode=st.session_state.mode,
                next="",
                rag_context="",
                rag_tier="",
                raw_query=prompt,
                contract_result={},
            )
            
            result = agent.invoke(input_state)
            
            assistant_messages = [
                msg for msg in result.get("messages", []) 
                if isinstance(msg, dict) and msg.get("role") == "assistant"
            ]
            
            if assistant_messages:
                response_content = assistant_messages[-1].get("content", "No response generated.")
            else:
                response_content = "No response generated by the agent."

            with st.chat_message("assistant"):
                if st.session_state.mode == "contract" and result.get("contract_result"):
                    contract_data = result["contract_result"]
                    
                    if isinstance(contract_data, str):
                        try:
                            contract_data = json.loads(contract_data)
                        except Exception:
                            pass
                    
                    if isinstance(contract_data, dict) and "risk_level" in contract_data:
                        risk_level = contract_data.get('risk_level', 'UNKNOWN')
                        risk_score = contract_data.get('overall_risk_score', 0)
                        
                        if risk_level in ["HIGH", "CRITICAL"]:
                            st.error(f"📄 Contract Analysis: **{risk_level} RISK**")
                        elif risk_level == "MEDIUM":
                            st.warning(f"📄 Contract Analysis: **{risk_level} RISK**")
                        else:
                            st.success(f"📄 Contract Analysis: **{risk_level} RISK**")
                            
                        st.metric("Overall Risk Score", f"{risk_score}/10")
                        st.markdown(f"**Executive Summary:** {contract_data.get('summary', 'N/A')}")
                        
                        with st.expander("🚨 Identified Issues & Red Flags"):
                            issues = contract_data.get("issues", [])
                            if not issues:
                                st.info("No major issues detected.")
                            for issue in issues:
                                st.markdown(f"**{issue.get('flag', 'Issue')}** (Risk: {issue.get('risk_score', 0)}/10)")
                                st.caption(f"*Excerpt:* \"{issue.get('excerpt', '')}\"")
                                st.markdown(f"*Impact:* {issue.get('impact', '')}")
                                st.success(f"*Suggested Revision:* {issue.get('suggested_revision', '')}")
                                st.divider()
                                
                        with st.expander("✅ Positive Clauses"):
                            pos = contract_data.get("positive_clauses", [])
                            st.write(pos if pos else "None identified.")
                            
                        with st.expander("⚠️ Missing Clauses"):
                            miss = contract_data.get("missing_clauses", [])
                            st.write(miss if miss else "None identified.")
                            
                        with st.expander("💡 Recommendations"):
                            rec = contract_data.get("recommendations", [])
                            st.write(rec if rec else "None.")
                            
                        with st.expander("Raw JSON Output"):
                            st.json(contract_data)
                    else:
                        st.markdown(response_content)
                else:
                    st.markdown(response_content)

            st.session_state.messages.append({"role": "assistant", "content": response_content})

        except RateLimitError as e:
            error_msg = f"⚠️ {str(e)}"
            st.warning(error_msg)
            st.session_state.messages.append({"role": "assistant", "content": error_msg})
        except Exception as e:
            error_msg = str(e).lower()
            if "503" in error_msg or "unavailable" in error_msg:
                display_msg = "⚠️ **Service Temporarily Unavailable**: The AI service is experiencing high demand. Please wait a moment and try again."
            else:
                display_msg = f"⚠️ An error occurred: {str(e)}"
            st.error(display_msg)
            st.session_state.messages.append({"role": "assistant", "content": display_msg})